name: Build & Test - Manual

on: workflow_dispatch

jobs:
  build:
    name: All Steps (Build, Test & Deploy)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: ng test --browsers ChromeHeadless --code-coverage
